code --install-extension akamud.vscode-theme-onedark
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cssho.vscode-svgviewer
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension Equinusocio.vsc-material-theme
code --install-extension HookyQR.beautify
code --install-extension ionutvmi.path-autocomplete
code --install-extension joelday.docthis
code --install-extension jpoissonnier.vscode-styled-components
code --install-extension jtlowe.vscode-icon-theme
code --install-extension ms-azuretools.vscode-docker
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension silvenon.mdx
code --install-extension tinaciousdesign.theme-tinaciousdesign
code --install-extension vscode-icons-team.vscode-icons
code --install-extension waderyan.gitblame
code --install-extension WallabyJs.quokka-vscode
code --install-extension whizkydee.material-palenight-theme
code --install-extension wix.vscode-import-cost
